### ISSUE TITLE
Ustengrav - Void on door

### ISSUE THREAD

**Issue by cethien** [ErikJohnsson/DungeonsRevisited#34] opened 2021-01-18 16:43 UTC
![ScreenShot5](https://user-images.githubusercontent.com/60463918/104942124-529df100-59b4-11eb-8652-e2999372e5fb.png)
- can't tell which room, therefor the coordinates.
- when going through the void, it vanishes.
- no ENB, only ELFX and Vivid Weathers for lighting

**Comment by ErikJohnsson** [comment] 2023-01-14 20:30
Cant reproduce. Closing.

**Closed as completed by ErikJohnsson** 2023-01-14 20:30 UTC
Labels: bug
