### ISSUE TITLE
Embershard mine revisited - minor issues

### ISSUE THREAD

**Issue by Neurosavant** [ErikJohnsson/DungeonsRevisited#27] opened 2020-11-03 13:37 UTC
Hi

Some screens of some minor issues in EMR.  Thanks for the mod.  Endorsed on Nexus. :)
![ember4](https://user-images.githubusercontent.com/34976323/97991585-869e5700-1e46-11eb-9d79-141a056b81cc.jpg)
![Ember5](https://user-images.githubusercontent.com/34976323/97991590-88681a80-1e46-11eb-9282-e0a59b604a08.jpg)
![ember1](https://user-images.githubusercontent.com/34976323/97991593-88681a80-1e46-11eb-8f91-437fccc75b21.jpg)
![ember2](https://user-images.githubusercontent.com/34976323/97991597-8900b100-1e46-11eb-95d1-e0f0f5848ea5.jpg)
![ember3](https://user-images.githubusercontent.com/34976323/97991599-89994780-1e46-11eb-94f8-0b541a4e782a.jpg)

**Comment by ErikJohnsson** [comment] 2020-11-04 19:34
Some of the issues I could find and fix but im confused by these pictures

![](https://user-images.githubusercontent.com/34976323/97991593-88681a80-1e46-11eb-8f91-437fccc75b21.jpg)

![](https://user-images.githubusercontent.com/34976323/97991585-869e5700-1e46-11eb-9d79-141a056b81cc.jpg)

**Comment by Neurosavant** [comment] 2020-11-04 19:38
Is it not something to do with the occlusion planes?  Sorry it's been a while since I've done level design in the CK.

**Comment by Neurosavant** [comment] 2020-11-06 20:42
I took a look in the CK to see if I could see anything unusual and then I tried to replicate the two issues you weren't sure about.  Try as I might, I couldn't replicate them.  So they can be ignored.

**Comment by Neurosavant** [comment] 2020-11-07 19:47
Sorry to revisit this but I did inadvertently manage to replicate this when i was testing a lighting mod.  It occurs when you exit and re-enter the mine, although I'm still unsure why.

**Comment by ErikJohnsson** [comment] 2020-11-08 09:57
Yeah lighting mods are almost always incompatible because of occlusion planes.

**Comment by Neurosavant** [comment] 2020-11-08 13:51
You misunderstand.  I wasn't using a lighting mod when I first encountered the bug.  I had only your mod and USSEP in my load order.  I was able to replicate the bug the second time with only your mod in my load order, by exiting and re-entering the mine.

**Comment by ErikJohnsson** [comment] 2020-11-19 11:52
Oh okay. Hm, interesting. I'll see what I can do.

**Comment by Lorx92** [comment] 2021-07-12 05:36
I second this, in Embershard Mines, I encountered multiple Issues, some of them the same as above, additionally also sound problems when swimming or diving in the new water areas. It is also possible to clip completely out of the map. The sound problems can also be related to the Immersive Sounds of Skyrim mod.

**Comment by ErikJohnsson** [comment] 2023-01-14 20:35
Can't reproduce issues. Closing until more info is given.

**Closed as completed by ErikJohnsson** 2023-01-14 20:35 UTC
Labels: bug
